const propiedades=[{nombre:"Galileo Galilei",
                    pais:"Italia",
                    imagen:"Galileo",
                    cargo:"Matemático",
                    empresa:"1564-1642",
                    testimonio1:"Las",
                    testimonion:"matemáticas",
                    testimonio2:"son el lenguaje con el que dios ha escrito el universo."},
                  {nombre:"Frank Capra",
                  pais:"Italia",
                  imagen:"Frank",
                  cargo:"Cineasta",
                  empresa:"1897-1991",
                  testimonio1:"El cine es uno de los tres lenguajes universales, los otros dos: las",
                  testimonion:"matemáticas",
                  testimonio2:"y la música."},
                  {nombre:"Neil deGrasse Tyson",
                  pais:"Estados Unidos",
                  imagen:"Neil",
                  cargo:"Astrónomo",
                  empresa:"1958-*",
                  testimonio1:"Hay gente que dice: 'Nunca voy a necesitar las matemáticas' como la trigonometría que se da la secundaria o bachillerato. Incluso puede que tú nunca hayas aprendido algo de matemáticas. Ahí está el truco: vayas o no a usar las matemáticas en tu vida, el hecho de que hayas sido capaz de entenderlas deja una huella en tu cerebro que no existia antes",
                  testimonion:"y esa huella es la que te convierte en un solucionador de problemas."}]
export default propiedades
